/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as EnquireRouteImport } from './routes/enquire'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesHolidaysRouteImport } from './routes/services.holidays'
import { Route as ServicesStudyAbroadRouteImport } from './routes/services.study-abroad'
import { Route as ServicesVisaRouteImport } from './routes/services.visa'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquireRoute = EnquireRouteImport.update({
  id: '/enquire',
  path: '/enquire',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DestinationsRoute,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DestinationsRoute,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuidesRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesHolidaysRoute = ServicesHolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesStudyAbroadRoute = ServicesStudyAbroadRouteImport.update({
  id: '/study-abroad',
  path: '/study-abroad',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesVisaRoute = ServicesVisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/enquire': typeof EnquireRoute
  '/faq': typeof FaqRoute
  '/guides': typeof GuidesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/services/holidays': typeof ServicesHolidaysRoute
  '/services/study-abroad': typeof ServicesStudyAbroadRoute
  '/services/visa': typeof ServicesVisaRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/enquire': typeof EnquireRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/services/holidays': typeof ServicesHolidaysRoute
  '/services/study-abroad': typeof ServicesStudyAbroadRoute
  '/services/visa': typeof ServicesVisaRoute
  '/destinations': typeof DestinationsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/enquire': typeof EnquireRoute
  '/faq': typeof FaqRoute
  '/guides': typeof GuidesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/services/holidays': typeof ServicesHolidaysRoute
  '/services/study-abroad': typeof ServicesStudyAbroadRoute
  '/services/visa': typeof ServicesVisaRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/destinations'
    | '/enquire'
    | '/faq'
    | '/guides'
    | '/privacy'
    | '/services'
    | '/destinations/$slug'
    | '/guides/$slug'
    | '/services/holidays'
    | '/services/study-abroad'
    | '/services/visa'
    | '/destinations/'
    | '/guides/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/enquire'
    | '/faq'
    | '/privacy'
    | '/destinations/$slug'
    | '/guides/$slug'
    | '/services/holidays'
    | '/services/study-abroad'
    | '/services/visa'
    | '/destinations'
    | '/guides'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/destinations'
    | '/enquire'
    | '/faq'
    | '/guides'
    | '/privacy'
    | '/services'
    | '/destinations/$slug'
    | '/guides/$slug'
    | '/services/holidays'
    | '/services/study-abroad'
    | '/services/visa'
    | '/destinations/'
    | '/guides/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
  EnquireRoute: typeof EnquireRoute
  FaqRoute: typeof FaqRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquire': {
      id: '/enquire'
      path: '/enquire'
      fullPath: '/enquire'
      preLoaderRoute: typeof EnquireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/guides/': {
      id: '/guides/'
      path: '/'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/holidays': {
      id: '/services/holidays'
      path: '/holidays'
      fullPath: '/services/holidays'
      preLoaderRoute: typeof ServicesHolidaysRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/study-abroad': {
      id: '/services/study-abroad'
      path: '/study-abroad'
      fullPath: '/services/study-abroad'
      preLoaderRoute: typeof ServicesStudyAbroadRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/visa': {
      id: '/services/visa'
      path: '/visa'
      fullPath: '/services/visa'
      preLoaderRoute: typeof ServicesVisaRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface DestinationsRouteChildren {
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsSlugRoute: DestinationsSlugRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

interface ServicesRouteChildren {
  ServicesHolidaysRoute: typeof ServicesHolidaysRoute
  ServicesStudyAbroadRoute: typeof ServicesStudyAbroadRoute
  ServicesVisaRoute: typeof ServicesVisaRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesHolidaysRoute: ServicesHolidaysRoute,
  ServicesStudyAbroadRoute: ServicesStudyAbroadRoute,
  ServicesVisaRoute: ServicesVisaRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
  EnquireRoute: EnquireRoute,
  FaqRoute: FaqRoute,
  GuidesRoute: GuidesRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
